### ISSUE TITLE
The latest validator is not available in S3

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/validator-short-read-assembler#28]
When I download the new current validator with 

wget https://s3-us-west-1.amazonaws.com/bioboxes-tools/validate-short-read-assembler/0.x.y/validate-short-read-assembler.tar.gz

It is not the latest one based on the failing tests.

**Comment by michaelbarton** [comment]
I'll rebuild this on the ci server and see if this fixes the problem.

**Comment by michaelbarton** [comment]
Did you download the file manually when this happened or was it part of a
`docker build`? I had a similar problem where the updated file-validator
output was not shown, however this was because the docker daemon was using
an image layer containing 0.1.1 as opposed to downloading the latest
version. I cleared all my local images and reran the SRA validator tests
and this worked.

I think a solution to this would be to use a 0.1.x -> 0.2.x version update
for this kind of change. We would then recommend using the 0.2.x download
in Dockerfiles so that a pathc change would force a rebuild of that image
layer. We may even want to consider removing 0.x.y altogether because this
bug is somewhat insidious as, at least in my case and on the CI server, it
appears to point to the incorrect file being available rather than the real
cause which is the cached image layer being used.

**Comment by pbelmann** [comment]
I downloaded the file manualy because I just wanted to test the documentation on bioboxes.org.
But yes it could be that the newest file-validator is not downloaded because of the cache. I`ll test it.

**Comment by michaelbarton** [comment]
Ok. In any case I have reuploaded the 0.1.2 verson to S3. If that doesn't
work then there must be a bug somewhere else in the deployment scripts.

**Comment by pbelmann** [comment]
Ok I run 

`docker build --no-cache -t velvet .`

and run the documented validator commands:

``` shell
# Fetch the latest 0.1.x release of the validator
wget https://s3-us-west-1.amazonaws.com/bioboxes-tools/validate-short-read-assembler/0.1.x/validate-short-read-assembler.tar.gz
tar xzf validate-short-read-assembler.tar.gz

./validate-short-read-assembler/validate bioboxes/velvet default
```

But still without success. 

>  I cleared all my local images and reran the SRA validator tests
> and this worked.

Is removing the images really a difference to --no-cache?

**Comment by michaelbarton** [comment]
This is my mistake. I thought we were discussing the file-validator not the
SRA validator. I saw the `wget` url and realised what I was doing wrong. A
new version is deployed if the VERSION number is incremented. This meant
the file-validator was deployed with a new version, but the SRA validator
with the new feature files was not deployed. I will do this now.

**Comment by michaelbarton** [comment]
I have bumped this to 0.2.0 as this feature tested outputs have all
changed. In about five minutes the new version should be available.

**Comment by pbelmann** [comment]
Ah ok. Actually it's my fault because I forgot to update version file in the json-schema PR. Thanks Michael.
